node {
    stage('Teste') {
        env.JAVA_HOME = tool 'java14'
        checkout scm
        sh 'ls -la'
        sh 'git status'
        sh 'git branch'
        sh './gradlew clean build -x test'
    }
}