node {
    stage('Teste') {
        env.JAVA_HOME = tool 'java14'
        SCM_VARS = checkout scm
        env.GIT_BRANCH = SCM_VARS.GIT_BRANCH.replace(/origin\//, "")
        print SCM_VARS
        sh 'ls -la'
        sh 'git status'
        sh 'git branch'
//        sh './gradlew clean build -x test'
    }
}